### PR TITLE
Add missing offsets for 10.50

### PR DESCRIPTION
**Pull request by BestPig**
I tested multiple payloads on a real PS4 10.50 FW
- module_dumper / pup_decrypter was working
- Usb Loader was working
- Debug Settings is enabled correctly

So all offsets should be OK

### CODE REVIEW

**Review by jalarcon666 — COMMENTED** [review]
I try at 10.50 and we'll see how it goes! THANK YOU!!

**Comment by jalarcon666** [comment]
Debug menu and payloads module_dumper/pup_decrypter working on 10.50, thanks!! a question. Can you think of how to update by skipping the blu-ray reader driver validation?

photo_2024-05-26_00-15-46
photo_2024-05-26_00-15-35

**Review by jalarcon666 — APPROVED** [review]
Debug menu and payloads module_dumper/pup_decrypter working on 10.50, correct offsets and no compilation errors

**Comment by BestPig** [comment]
> Debug menu and payloads module_dumper/pup_decrypter working on 10.50, thanks!! a question. Can you think of how to update by skipping the blu-ray reader driver validation?
> 

I have no idea, the existing ps4 nobd updater for upgrading to 9.0 is not OpenSource, so hard to port, time will tell.
